# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFihFHB8hCnVsuLbz3MN3YhSaddz6ida

# ERP Tabanlı Müşteri Analitiği Projesi

Bu projede müşteri verileri analiz edilerek RFM segmentasyonu, churn analizi ve Pareto analizi gerçekleştirilmiştir.
"""

import pandas as pd
import numpy as np
import sqlite3

df = pd.read_csv("flo_data_20k.csv")

df.head(5)

df.shape

df.info()

df.describe().T

df.isnull().sum()

df.duplicated().sum()

df["interested_in_categories_12"].value_counts().head(5)

# Toplam müşteri sayısı
df["master_id"].nunique()

df[["order_num_total_ever_online", "order_num_total_ever_offline"]].mean()

df[["customer_value_total_ever_online", "customer_value_total_ever_offline"]].mean()

df["total_order_num"] = df["order_num_total_ever_online"] + df["order_num_total_ever_offline"] #Online ve offline satışları topladık.

df["total_customer_value"] = (df["customer_value_total_ever_online"] + df["customer_value_total_ever_offline"]) #Online ve offline toplam harcamalar.

df["avg_order_value"] = df["total_customer_value"] / df["total_order_num"] #Bu ikisinin bölerek ortalama siparişi hesapladım.

# Toplam gelir
df["total_customer_value"].sum()

df["first_order_date_dt"] = pd.to_datetime(df["first_order_date"])
df["last_order_date_dt"] = pd.to_datetime(df["last_order_date"])
# Burada firstorderdate sütunundaki değerler string'ti onu doğru forma soktum.

df[["first_order_date_dt","last_order_date_dt"]].head()

df["avg_order_value"]

df["avg_order_value"].describe().round(0)

df[["total_order_num", "total_customer_value", "avg_order_value"]].describe().T
# Müşterilerin sipariş sayısı, toplam harcaması ve ortalama sipariş değeri incelenmiştir.
# Ortalama sipariş sayısı 5'dir. Sapmanın bu kadar yüksek olması tüketici profili olarak geniş bir kitle olduğunu gösterir.

df["customer_life"] = (df["last_order_date_dt"] - df["first_order_date_dt"]).dt.days.astype("Int64")

df[["last_order_date_dt","first_order_date_dt","customer_life"]].sort_values(by="customer_life", ascending=False).head()
# Burada en uzun süreli ilk 5 müşteri ve tarihleri verilmiştir.

df.loc[df["customer_life"].idxmax()] #Burda ise en uzun süredir alışveriş yapan kullanıcının istatistikleri yer alıyor.

df.nlargest(5, "total_customer_value")[["master_id","total_customer_value"]]
#En yüksek harcama yapan müşterileri inceleme

df.nlargest(5, "total_order_num")[["master_id","total_order_num"]]

df.groupby("order_channel")["total_customer_value"].sum().sort_values(ascending=False)
#Android platformu toplam gelirde lider konumda iken;

df.groupby("order_channel")["total_customer_value"].mean().sort_values(ascending=False)
#iOS kullanıcıları müşteri başına daha yüksek harcama yaparak daha değerli bir segment oluşturmaktadır.

# Kanal bazlı müşteri sayısı
df.groupby("order_channel")["master_id"].nunique()

channel_sales = df.groupby("order_channel")["total_customer_value"].sum().sort_values(ascending=False)

(channel_sales / channel_sales.sum()) * 100

today_date = df["last_order_date_dt"].max() + pd.Timedelta(days=1)

df["recency"] = (today_date - df["last_order_date_dt"]).dt.days.astype("Int64")
# Recency değişkeni hesaplanarak müşterinin son alışverişinden bu yana geçen gün sayısı bulunmuştur.
# Bu metrik müşterinin ne kadar aktif olduğunu ve churn yani kaybedilme riskini analiz etmek için kullanılır.

rfm = df.groupby("master_id").agg({
    "recency": "min",
    "total_order_num": "sum",
    "total_customer_value": "sum"
})

rfm.columns = ["recency", "frequency", "monetary"]
# Müşteriler özelinde teker teker rfm tablosu yapılmıştır.

rfm["R_score"] = pd.qcut(rfm["recency"], 5, labels=[5,4,3,2,1])
rfm["F_score"] = pd.qcut(rfm["frequency"].rank(method="first"), 5, labels=[1,2,3,4,5])
rfm["M_score"] = pd.qcut(rfm["monetary"], 5, labels=[1,2,3,4,5])
# Rfm metrikleri 5 e kadar sıralandı.
#Recencynin düşük olmasının sebebi recency ters çalışır.Düşük olan yani yakın zamanda alışveriş yapan müşterilere yüksek skor 5 verilmiştir.
# Frequency ve Monetary değerleri yüksek olan müşterilere ise daha yüksek skorlar atanmıştır.
# Bu skorlar sayesinde müşteriler davranışlarına göre karşılaştırılabilir hale getirilmiştir.

rfm["RFM_SCORE"] = rfm["R_score"].astype(str) + rfm["F_score"].astype(str)
# Monetary neden dışarıda derseniz bazı müşteriler az alışveriş yapar ama pahalı ürün alır
#bazıları çok alışveriş yapar ama ucuz bu segmentasyonu bozabilir.

seg_map = {
    r"[1-2][1-2]": "hibernating",
    r"[1-2][3-4]": "at_risk",
    r"[1-2]5": "cant_lose",
    r"3[1-2]": "about_to_sleep",
    r"33": "need_attention",
    r"[3-4][4-5]": "loyal_customers",
    r"41": "promising",
    r"51": "new_customers",
    r"[4-5][2-3]": "potential_loyalists",
    r"5[4-5]": "champions"
}

rfm["segment"] = rfm["RFM_SCORE"].replace(seg_map, regex=True)
# Bu segmentler sayesinde müşterilerin davranışları anlamlandırılmıştır
# Örneğin 55 champions en iyi müşteri 11 hibernating pasif müşteri 15 cant_lose kaybedilmemeli gibi
# Böylece her müşteri grubuna özel pazarlama ve iş stratejileri geliştirilebilir.

rfm["segment"].value_counts() #Burada da yukarıda yaptığımızın sonuçları.
# En büyük grubun hibernating olduğu görülüyor.
# Bu durum müşteri kitlesinin önemli bir kısmının uzun süredir aktif olmadığını ve yeniden kazanım stratejilerine ihtiyaç duyulduğunu gösteriyor.
# Loyal_customers ve champions segmentlerinin de yüksek sayıda olması, mevcut aktif ve değerli müşteri kitlesinin güçlü olduğunu gösteriyor.
# At_risk ve cant_lose segmentleri ise geçmişte değerli olup şu an kaybedilme riski taşıyan müşterileri ifade ediyor.

rfm.groupby("segment").agg({
    "recency": "mean",
    "frequency": "mean",
    "monetary": "mean"
    }).sort_values("monetary", ascending=False)
# Bu sonuçlara göre cant_lose ve champions segmentlerinin en yüksek harcama (monetary) değerine sahip olduğu görülmektedir.
# Champions segmenti düşük recency değeri ile aktif ve yüksek frekanslı alışveriş yapan en değerli müşteri grubunu temsil etmektedir.
# Cant_lose segmenti ise yüksek harcama ve frekansa sahip olmasına rağmen yüksek recency değeri ile uzun süredir alışveriş yapmayan kritik müşterileri göstermektedir.
# Loyal_customers segmenti düzenli alışveriş yapan ve istikrarlı gelir sağlayan müşteri grubudur.
# Hibernating ve "about_to_sleep" segmentleri düşük frekans ve düşük harcama değerleri ile pasif müşteri kitlesini temsil etmektedir.
# Bu analiz, hangi müşteri segmentine nasıl aksiyon alınması gerektiğini belirlemek açısından önemli bir yol gösteriyor.

df.nlargest(5, "recency")[["master_id","recency"]]

df["churn"] = df["recency"] > 90 # Yani 90 günden beri yoksa müşteri kaybedilmiş churn olarak adlandırılıcak.

df["churn"].value_counts()
#Sonuçlar incelendiğinde churn olan müşteri sayısının,
#Churn olmayanlardan daha fazla olduğu görülmektedir.

df["churn"].mean() * 100

df.groupby("churn").agg({
    "total_customer_value": "mean",
    "total_order_num": "mean",
    "customer_life": "mean"
})
# Churn olan ve olmayan müşteriler karşılaştırıldığında, aktif müşterilerin (churn=False) daha yüksek ortalama harcama yaptığı görülmektedir.
# Ayrıca aktif müşterilerin ortalama sipariş sayısının daha fazla olduğu, yani daha sık alışveriş yaptıkları anlaşılmaktadır.
# Müşteri yaşam süresi (customer_life) incelendiğinde ise aktif müşterilerin daha uzun süre sistemde kaldığı görülmektedir.
# Churn olan müşteriler hem daha az alışveriş yapmakta hem de daha düşük gelir sağlamaktadır.

pareto = df.sort_values("total_customer_value", ascending=False)

pareto["cum_value"] = pareto["total_customer_value"].cumsum()

pareto["cum_ratio"] = pareto["cum_value"] / pareto["total_customer_value"].sum()

pareto["customer_ratio"] = np.arange(1, len(pareto)+1) / len(pareto)

pareto[pareto["cum_ratio"] <= 0.80].tail()
#Gelirin %80’inin %53 müşteri tarafından oluşturulduğu müşteri değerinin geniş bir kitleye yayıldığını ve yalnızca dar bir VIP segmentine bağlı olmadığını göstermektedir.

"""## Genel Değerlendirme ve Öneriler
###  Temel Bulgular



Müşterilerin ortalama sipariş sayısı yaklaşık 5 olup genel müşteri kitlesi orta seviyede alışveriş sıklığına sahiptir.  
Gelir dağılımı incelendiğinde bazı müşterilerin yüksek harcama yaptığı ve gelir dağılımının dengesiz olduğu gözlemlenmiştir.  
Kanal bazlı analizde Android uygulamasının toplam gelirde lider olduğu, ancak iOS kullanıcılarının müşteri başına daha yüksek harcama yaptığı görülmüştür.

RFM ve Segment Analizi

Champions ve Loyal Customers segmentleri en değerli müşteri grubunu oluşturmaktadır.  
Cant Lose segmenti yüksek harcama potansiyeline sahip olmasına rağmen uzun süredir alışveriş yapmayan kritik müşterileri temsil etmektedir.  
Hibernating segmentinin en büyük grup olması müşteri kitlesinin önemli bir kısmının pasif olduğunu göstermektedir.

Churn Analizi

Churn olan müşteri sayısının aktif müşterilerden fazla olması müşteri kaybının önemli bir problem olduğunu göstermektedir.  
Aktif müşterilerin daha yüksek harcama, daha fazla sipariş ve daha uzun müşteri yaşam süresine sahip olduğu görülmüştür.  
Bu durum müşteri sadakatinin doğrudan gelir ile ilişkili olduğunu ortaya koymaktadır.

Pareto Analizi

Toplam gelirin yüzde 80’i müşteri kitlesinin yaklaşık yüzde 53’ü tarafından oluşturulmaktadır.  
Bu sonuç gelir dağılımının belirli bir müşteri grubunda yoğunlaştığını ancak klasik 80 20 kuralına tam olarak uymadığını göstermektedir.  
Gelirin geniş bir müşteri kitlesine yayılmış olması farklı segmentler için farklı stratejiler geliştirilmesi gerektiğini ortaya koymaktadır.

İş Önerileri

Pasif müşteriler için yeniden kazanım kampanyaları geliştirilmelidir.  
Cant Lose segmentine özel promosyonlar ve kişiselleştirilmiş teklifler sunulmalıdır.  
Champions ve Loyal Customers segmentleri için sadakat programları oluşturulmalıdır.  
iOS kullanıcılarının yüksek harcama potansiyeli göz önünde bulundurularak premium ürün ve kampanyalar geliştirilebilir.  
Android platformunda geniş müşteri kitlesi korunmalı ve kullanıcı sayısı artırılmaya devam edilmelidir.

Sonuç

Bu analizler sonucunda müşteri davranışları detaylı şekilde incelenmiş yüksek değerli müşteriler belirlenmiş ve müşteri kaybını azaltmaya yönelik stratejik öneriler geliştirilmiştir. Proje ERP sistemlerinde kullanılabilecek müşteri analitiği yaklaşımını yansıtmaktadır.
"""